//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTTimeline.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String_ko_KR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String_ko_KR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACTTimeline.resources.String_ko-KR", typeof(String_ko_KR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT 타임라인.
        /// </summary>
        internal static string _ACT_Timeline {
            get {
                return ResourceManager.GetString("_ACT_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}개의 사운드 파일을 찾았습니다. .
        /// </summary>
        internal static string _Found_N_sound_files {
            get {
                return ResourceManager.GetString("_Found_N_sound_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}개의 타임라인 파일을 찾았습니다..
        /// </summary>
        internal static string _Found_N_timeline_txt_files {
            get {
                return ResourceManager.GetString("_Found_N_timeline_txt_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리소스 폴더를 찾았습니다! .
        /// </summary>
        internal static string _Resource_dir_exists {
            get {
                return ResourceManager.GetString("_Resource_dir_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리소스 폴더를 찾을 수 없습니다..
        /// </summary>
        internal static string _Resource_dir_not_found {
            get {
                return ResourceManager.GetString("_Resource_dir_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타임라인.
        /// </summary>
        internal static string _Show_Timeline {
            get {
                return ResourceManager.GetString("_Show_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wav 폴더를 찾을 수 없습니다..
        /// </summary>
        internal static string _Sound_files_dir_not_found {
            get {
                return ResourceManager.GetString("_Sound_files_dir_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeline 폴더를 찾을 수 없습니다..
        /// </summary>
        internal static string _Timeline_txt_files_dir_not_found {
            get {
                return ResourceManager.GetString("_Timeline_txt_files_dir_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글꼴 선택.
        /// </summary>
        internal static string buttonFontSelect {
            get {
                return ResourceManager.GetString("buttonFontSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글꼴 선택.
        /// </summary>
        internal static string buttonFontSelect2 {
            get {
                return ResourceManager.GetString("buttonFontSelect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글꼴 선택.
        /// </summary>
        internal static string buttonFontSelect3 {
            get {
                return ResourceManager.GetString("buttonFontSelect3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글꼴 선택.
        /// </summary>
        internal static string buttonFontSelect4 {
            get {
                return ResourceManager.GetString("buttonFontSelect4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글꼴 선택.
        /// </summary>
        internal static string buttonFontSelect5 {
            get {
                return ResourceManager.GetString("buttonFontSelect5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불러오기.
        /// </summary>
        internal static string buttonLoad {
            get {
                return ResourceManager.GetString("buttonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일시정지.
        /// </summary>
        internal static string buttonPause {
            get {
                return ResourceManager.GetString("buttonPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시작.
        /// </summary>
        internal static string buttonPlay {
            get {
                return ResourceManager.GetString("buttonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새로고침.
        /// </summary>
        internal static string buttonRefreshList {
            get {
                return ResourceManager.GetString("buttonRefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 폴더열기.
        /// </summary>
        internal static string buttonResourceDirOpen {
            get {
                return ResourceManager.GetString("buttonResourceDirOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 되감기.
        /// </summary>
        internal static string buttonRewind {
            get {
                return ResourceManager.GetString("buttonRewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 닫기.
        /// </summary>
        internal static string buttonUnload {
            get {
                return ResourceManager.GetString("buttonUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오버레이 자동 숨김.
        /// </summary>
        internal static string checkBoxAutohide {
            get {
                return ResourceManager.GetString("checkBoxAutohide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 지역이 바뀌면 자동으로 불러오기.
        /// </summary>
        internal static string checkBoxAutoloadAfterChangeZone {
            get {
                return ResourceManager.GetString("checkBoxAutoloadAfterChangeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리셋 시 타임라인 일시정지 및 되감기.
        /// </summary>
        internal static string checkBoxAutoStop {
            get {
                return ResourceManager.GetString("checkBoxAutoStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 마우스 클릭 허용.
        /// </summary>
        internal static string checkBoxMoveOverlayByDrag {
            get {
                return ResourceManager.GetString("checkBoxMoveOverlayByDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 마우스 클릭 허용.
        /// </summary>
        internal static string checkBoxMoveOverlayByDrag2 {
            get {
                return ResourceManager.GetString("checkBoxMoveOverlayByDrag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 마우스 클릭 허용.
        /// </summary>
        internal static string checkBoxMoveOverlayByDrag3 {
            get {
                return ResourceManager.GetString("checkBoxMoveOverlayByDrag3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 마우스 클릭 허용.
        /// </summary>
        internal static string checkBoxMoveOverlayByDrag4 {
            get {
                return ResourceManager.GetString("checkBoxMoveOverlayByDrag4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 마우스 클릭 허용.
        /// </summary>
        internal static string checkBoxMoveOverlayByDrag5 {
            get {
                return ResourceManager.GetString("checkBoxMoveOverlayByDrag5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10초 이상 남은 항목 표시.
        /// </summary>
        internal static string checkBoxOver10 {
            get {
                return ResourceManager.GetString("checkBoxOver10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10초 이상 남은 항목 표시.
        /// </summary>
        internal static string checkBoxOver102 {
            get {
                return ResourceManager.GetString("checkBoxOver102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10초 이상 남은 항목 표시.
        /// </summary>
        internal static string checkBoxOver103 {
            get {
                return ResourceManager.GetString("checkBoxOver103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10초 이상 남은 항목 표시.
        /// </summary>
        internal static string checkBoxOver104 {
            get {
                return ResourceManager.GetString("checkBoxOver104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10초 이상 남은 항목 표시.
        /// </summary>
        internal static string checkBoxOver105 {
            get {
                return ResourceManager.GetString("checkBoxOver105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시.
        /// </summary>
        internal static string CheckBoxOverlayVisible {
            get {
                return ResourceManager.GetString("CheckBoxOverlayVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시.
        /// </summary>
        internal static string CheckBoxOverlayVisible2 {
            get {
                return ResourceManager.GetString("CheckBoxOverlayVisible2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시.
        /// </summary>
        internal static string CheckBoxOverlayVisible3 {
            get {
                return ResourceManager.GetString("CheckBoxOverlayVisible3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시.
        /// </summary>
        internal static string CheckBoxOverlayVisible4 {
            get {
                return ResourceManager.GetString("CheckBoxOverlayVisible4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시.
        /// </summary>
        internal static string CheckBoxOverlayVisible5 {
            get {
                return ResourceManager.GetString("CheckBoxOverlayVisible5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT를 통해 소리 재생.
        /// </summary>
        internal static string checkBoxPlaySoundByACT {
            get {
                return ResourceManager.GetString("checkBoxPlaySoundByACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 팝업 모드.
        /// </summary>
        internal static string checkBoxPopup {
            get {
                return ResourceManager.GetString("checkBoxPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 팝업 모드.
        /// </summary>
        internal static string checkBoxPopup2 {
            get {
                return ResourceManager.GetString("checkBoxPopup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 팝업 모드.
        /// </summary>
        internal static string checkBoxPopup3 {
            get {
                return ResourceManager.GetString("checkBoxPopup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 팝업 모드.
        /// </summary>
        internal static string checkBoxPopup4 {
            get {
                return ResourceManager.GetString("checkBoxPopup4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 팝업 모드.
        /// </summary>
        internal static string checkBoxPopup5 {
            get {
                return ResourceManager.GetString("checkBoxPopup5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시 순서를 역방향으로.
        /// </summary>
        internal static string checkBoxReverseOrder {
            get {
                return ResourceManager.GetString("checkBoxReverseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시 순서를 역방향으로.
        /// </summary>
        internal static string checkBoxReverseOrder2 {
            get {
                return ResourceManager.GetString("checkBoxReverseOrder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시 순서를 역방향으로.
        /// </summary>
        internal static string checkBoxReverseOrder3 {
            get {
                return ResourceManager.GetString("checkBoxReverseOrder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시 순서를 역방향으로.
        /// </summary>
        internal static string checkBoxReverseOrder4 {
            get {
                return ResourceManager.GetString("checkBoxReverseOrder4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시 순서를 역방향으로.
        /// </summary>
        internal static string checkBoxReverseOrder5 {
            get {
                return ResourceManager.GetString("checkBoxReverseOrder5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시전 중인 항목 표시.
        /// </summary>
        internal static string checkBoxShowCasting {
            get {
                return ResourceManager.GetString("checkBoxShowCasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시전 중인 항목 표시.
        /// </summary>
        internal static string checkBoxShowCasting2 {
            get {
                return ResourceManager.GetString("checkBoxShowCasting2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시전 중인 항목 표시.
        /// </summary>
        internal static string checkBoxShowCasting3 {
            get {
                return ResourceManager.GetString("checkBoxShowCasting3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시전 중인 항목 표시.
        /// </summary>
        internal static string checkBoxShowCasting4 {
            get {
                return ResourceManager.GetString("checkBoxShowCasting4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시전 중인 항목 표시.
        /// </summary>
        internal static string checkBoxShowCasting5 {
            get {
                return ResourceManager.GetString("checkBoxShowCasting5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 조작 버튼 표시.
        /// </summary>
        internal static string checkBoxShowOverlayButtons {
            get {
                return ResourceManager.GetString("checkBoxShowOverlayButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 조작 버튼 표시.
        /// </summary>
        internal static string checkBoxShowOverlayButtons2 {
            get {
                return ResourceManager.GetString("checkBoxShowOverlayButtons2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 조작 버튼 표시.
        /// </summary>
        internal static string checkBoxShowOverlayButtons3 {
            get {
                return ResourceManager.GetString("checkBoxShowOverlayButtons3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 조작 버튼 표시.
        /// </summary>
        internal static string checkBoxShowOverlayButtons4 {
            get {
                return ResourceManager.GetString("checkBoxShowOverlayButtons4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 조작 버튼 표시.
        /// </summary>
        internal static string checkBoxShowOverlayButtons5 {
            get {
                return ResourceManager.GetString("checkBoxShowOverlayButtons5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10초 미만 남은 항목 표시.
        /// </summary>
        internal static string checkBoxUnder10 {
            get {
                return ResourceManager.GetString("checkBoxUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10초 미만 남은 항목 표시.
        /// </summary>
        internal static string checkBoxUnder102 {
            get {
                return ResourceManager.GetString("checkBoxUnder102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10초 미만 남은 항목 표시.
        /// </summary>
        internal static string checkBoxUnder103 {
            get {
                return ResourceManager.GetString("checkBoxUnder103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10초 미만 남은 항목 표시.
        /// </summary>
        internal static string checkBoxUnder104 {
            get {
                return ResourceManager.GetString("checkBoxUnder104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10초 미만 남은 항목 표시.
        /// </summary>
        internal static string checkBoxUnder105 {
            get {
                return ResourceManager.GetString("checkBoxUnder105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 너비:.
        /// </summary>
        internal static string labelBar {
            get {
                return ResourceManager.GetString("labelBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 너비:.
        /// </summary>
        internal static string labelBar2 {
            get {
                return ResourceManager.GetString("labelBar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 너비:.
        /// </summary>
        internal static string labelBar3 {
            get {
                return ResourceManager.GetString("labelBar3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 너비:.
        /// </summary>
        internal static string labelBar4 {
            get {
                return ResourceManager.GetString("labelBar4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 너비:.
        /// </summary>
        internal static string labelBar5 {
            get {
                return ResourceManager.GetString("labelBar5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 행.
        /// </summary>
        internal static string labelColumnSize {
            get {
                return ResourceManager.GetString("labelColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 행.
        /// </summary>
        internal static string labelColumnSize2 {
            get {
                return ResourceManager.GetString("labelColumnSize2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 행.
        /// </summary>
        internal static string labelColumnSize3 {
            get {
                return ResourceManager.GetString("labelColumnSize3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 행.
        /// </summary>
        internal static string labelColumnSize4 {
            get {
                return ResourceManager.GetString("labelColumnSize4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 행.
        /// </summary>
        internal static string labelColumnSize5 {
            get {
                return ResourceManager.GetString("labelColumnSize5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글꼴:.
        /// </summary>
        internal static string labelFont {
            get {
                return ResourceManager.GetString("labelFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글꼴:.
        /// </summary>
        internal static string labelFont2 {
            get {
                return ResourceManager.GetString("labelFont2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글꼴:.
        /// </summary>
        internal static string labelFont3 {
            get {
                return ResourceManager.GetString("labelFont3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글꼴:.
        /// </summary>
        internal static string labelFont4 {
            get {
                return ResourceManager.GetString("labelFont4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글꼴:.
        /// </summary>
        internal static string labelFont5 {
            get {
                return ResourceManager.GetString("labelFont5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 불러온 타임라인 없음 --.
        /// </summary>
        internal static string labelLoadedTimeline {
            get {
                return ResourceManager.GetString("labelLoadedTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불러온 타임라인 :.
        /// </summary>
        internal static string labelLoadedTimelineLabel {
            get {
                return ResourceManager.GetString("labelLoadedTimelineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시할 행 갯수:.
        /// </summary>
        internal static string labelNumRows {
            get {
                return ResourceManager.GetString("labelNumRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시할 행 갯수:.
        /// </summary>
        internal static string labelNumRows2 {
            get {
                return ResourceManager.GetString("labelNumRows2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시할 행 갯수:.
        /// </summary>
        internal static string labelNumRows3 {
            get {
                return ResourceManager.GetString("labelNumRows3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시할 행 갯수:.
        /// </summary>
        internal static string labelNumRows4 {
            get {
                return ResourceManager.GetString("labelNumRows4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 표시할 행 갯수:.
        /// </summary>
        internal static string labelNumRows5 {
            get {
                return ResourceManager.GetString("labelNumRows5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불투명도:.
        /// </summary>
        internal static string labelOpacity {
            get {
                return ResourceManager.GetString("labelOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불투명도:.
        /// </summary>
        internal static string labelOpacity2 {
            get {
                return ResourceManager.GetString("labelOpacity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불투명도:.
        /// </summary>
        internal static string labelOpacity3 {
            get {
                return ResourceManager.GetString("labelOpacity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불투명도:.
        /// </summary>
        internal static string labelOpacity4 {
            get {
                return ResourceManager.GetString("labelOpacity4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불투명도:.
        /// </summary>
        internal static string labelOpacity5 {
            get {
                return ResourceManager.GetString("labelOpacity5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오버레이 위치.
        /// </summary>
        internal static string labelOverlayOrientation {
            get {
                return ResourceManager.GetString("labelOverlayOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오버레이 위치.
        /// </summary>
        internal static string labelOverlayOrientation2 {
            get {
                return ResourceManager.GetString("labelOverlayOrientation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오버레이 위치.
        /// </summary>
        internal static string labelOverlayOrientation3 {
            get {
                return ResourceManager.GetString("labelOverlayOrientation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오버레이 위치.
        /// </summary>
        internal static string labelOverlayOrientation4 {
            get {
                return ResourceManager.GetString("labelOverlayOrientation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오버레이 위치.
        /// </summary>
        internal static string labelOverlayOrientation5 {
            get {
                return ResourceManager.GetString("labelOverlayOrientation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리소스 디렉토리:.
        /// </summary>
        internal static string labelResourceDir {
            get {
                return ResourceManager.GetString("labelResourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 높이:.
        /// </summary>
        internal static string labelTextWidth {
            get {
                return ResourceManager.GetString("labelTextWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 높이:.
        /// </summary>
        internal static string labelTextWidth2 {
            get {
                return ResourceManager.GetString("labelTextWidth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 높이:.
        /// </summary>
        internal static string labelTextWidth3 {
            get {
                return ResourceManager.GetString("labelTextWidth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 높이:.
        /// </summary>
        internal static string labelTextWidth4 {
            get {
                return ResourceManager.GetString("labelTextWidth4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 높이:.
        /// </summary>
        internal static string labelTextWidth5 {
            get {
                return ResourceManager.GetString("labelTextWidth5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타임라인 조작.
        /// </summary>
        internal static string lblCtrl {
            get {
                return ResourceManager.GetString("lblCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타임라인 정보.
        /// </summary>
        internal static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타임라인 목록.
        /// </summary>
        internal static string lblList {
            get {
                return ResourceManager.GetString("lblList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타임라인 오버레이 설정.
        /// </summary>
        internal static string lblOverlaySet {
            get {
                return ResourceManager.GetString("lblOverlaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타임라인 설정.
        /// </summary>
        internal static string lblSettings {
            get {
                return ResourceManager.GetString("lblSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오버레이 1.
        /// </summary>
        internal static string tabPage1 {
            get {
                return ResourceManager.GetString("tabPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오버레이 2.
        /// </summary>
        internal static string tabPage2 {
            get {
                return ResourceManager.GetString("tabPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오버레이 3.
        /// </summary>
        internal static string tabPage3 {
            get {
                return ResourceManager.GetString("tabPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오버레이 4.
        /// </summary>
        internal static string tabPage4 {
            get {
                return ResourceManager.GetString("tabPage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오버레이 5.
        /// </summary>
        internal static string tabPage5 {
            get {
                return ResourceManager.GetString("tabPage5", resourceCulture);
            }
        }
    }
}
