//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTTimeline.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String_KR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String_KR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACTTimeline.resources.String_KR", typeof(String_KR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리소스 디렉토리를 선택하세요
        ///(선택한 폴더 아래에 &quot;/timeline&quot;폴더와 &quot;/wav&quot;폴더가 있어야 합니다.).
        /// </summary>
        internal static string _LN_PleaseSelectResDir {
            get {
                return ResourceManager.GetString("_LN_PleaseSelectResDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Started..
        /// </summary>
        internal static string _LN_PluginStarted {
            get {
                return ResourceManager.GetString("_LN_PluginStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리소스 디렉토리 찾음! .
        /// </summary>
        internal static string _LN_ResFound {
            get {
                return ResourceManager.GetString("_LN_ResFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리소스를 찾을 수 없어요 ㅠㅁC.
        /// </summary>
        internal static string _LN_ResNotFound {
            get {
                return ResourceManager.GetString("_LN_ResNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타임라인 보기.
        /// </summary>
        internal static string _LN_ShowTimeline {
            get {
                return ResourceManager.GetString("_LN_ShowTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT 타임라인.
        /// </summary>
        internal static string _LN_Tabname {
            get {
                return ResourceManager.GetString("_LN_Tabname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}개의 타임라인 파일을 찾았습니다..
        /// </summary>
        internal static string _LN_TimelineFound {
            get {
                return ResourceManager.GetString("_LN_TimelineFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  타임라인 폴더를 찾을 수 없습니다..
        /// </summary>
        internal static string _LN_TimelineNotFound {
            get {
                return ResourceManager.GetString("_LN_TimelineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}개의 사운드 파일을 찾았습니다..
        /// </summary>
        internal static string _LN_WavFound {
            get {
                return ResourceManager.GetString("_LN_WavFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  사운드 폴더를 찾을 수 없습니다..
        /// </summary>
        internal static string _LN_WavNotFound {
            get {
                return ResourceManager.GetString("_LN_WavNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글꼴 선택.
        /// </summary>
        internal static string buttonFontSelect {
            get {
                return ResourceManager.GetString("buttonFontSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불러오기.
        /// </summary>
        internal static string buttonLoad {
            get {
                return ResourceManager.GetString("buttonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일시정지.
        /// </summary>
        internal static string buttonPause {
            get {
                return ResourceManager.GetString("buttonPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 재생.
        /// </summary>
        internal static string buttonPlay {
            get {
                return ResourceManager.GetString("buttonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새로고침.
        /// </summary>
        internal static string buttonRefreshList {
            get {
                return ResourceManager.GetString("buttonRefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 폴더열기.
        /// </summary>
        internal static string buttonResourceDirOpen {
            get {
                return ResourceManager.GetString("buttonResourceDirOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택.
        /// </summary>
        internal static string buttonResourceDirSelect {
            get {
                return ResourceManager.GetString("buttonResourceDirSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 되감기.
        /// </summary>
        internal static string buttonRewind {
            get {
                return ResourceManager.GetString("buttonRewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자동 숨김.
        /// </summary>
        internal static string checkBoxAutohide {
            get {
                return ResourceManager.GetString("checkBoxAutohide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 지역이 바뀌면 자동으로 불러오기.
        /// </summary>
        internal static string checkBoxAutoloadAfterChangeZone {
            get {
                return ResourceManager.GetString("checkBoxAutoloadAfterChangeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 클릭 허용 (체크 해제시 클릭 통과됨).
        /// </summary>
        internal static string checkBoxMoveOverlayByDrag {
            get {
                return ResourceManager.GetString("checkBoxMoveOverlayByDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT를 통해 소리 재생.
        /// </summary>
        internal static string checkBoxPlaySoundByACT {
            get {
                return ResourceManager.GetString("checkBoxPlaySoundByACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 작은 컨트롤 버튼 보이기.
        /// </summary>
        internal static string checkBoxShowOverlayButtons {
            get {
                return ResourceManager.GetString("checkBoxShowOverlayButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타임라인 목록.
        /// </summary>
        internal static string groupBoxTimelines {
            get {
                return ResourceManager.GetString("groupBoxTimelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 행 너비.
        /// </summary>
        internal static string labelColumnSize {
            get {
                return ResourceManager.GetString("labelColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글꼴 :.
        /// </summary>
        internal static string labelFont {
            get {
                return ResourceManager.GetString("labelFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- 불러온 타임라인 없음 --.
        /// </summary>
        internal static string labelLoadedTimeline {
            get {
                return ResourceManager.GetString("labelLoadedTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 불러온 타임라인 :.
        /// </summary>
        internal static string labelLoadedTimelineLabel {
            get {
                return ResourceManager.GetString("labelLoadedTimelineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 보여질 열 갯수.
        /// </summary>
        internal static string labelNumRows {
            get {
                return ResourceManager.GetString("labelNumRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 투명도.
        /// </summary>
        internal static string labelOpacity {
            get {
                return ResourceManager.GetString("labelOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오버레이 위치.
        /// </summary>
        internal static string labelOverlayOrientation {
            get {
                return ResourceManager.GetString("labelOverlayOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 리소스 디렉토리 :.
        /// </summary>
        internal static string labelResourceDir {
            get {
                return ResourceManager.GetString("labelResourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타임라인 컨트롤.
        /// </summary>
        internal static string lblCtrl {
            get {
                return ResourceManager.GetString("lblCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타임라인 정보.
        /// </summary>
        internal static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 타임라인 목록.
        /// </summary>
        internal static string lblList {
            get {
                return ResourceManager.GetString("lblList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오버레이 설정.
        /// </summary>
        internal static string lblOverlaySet {
            get {
                return ResourceManager.GetString("lblOverlaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 일반.
        /// </summary>
        internal static string tabMain {
            get {
                return ResourceManager.GetString("tabMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설정.
        /// </summary>
        internal static string tabOption {
            get {
                return ResourceManager.GetString("tabOption", resourceCulture);
            }
        }
    }
}
